[package]
name = "korg-syro"
version = "0.1.0"
authors = ["Gustaf Lindstedt <gustaflindstedt@protonmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
korg-syro-sys = "0.1.0"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
waver = "0.1"